### ISSUE TITLE
npm i eth-keyring-controller npm ERR! code ENOSELF

### ISSUE THREAD

**Issue by zhangyi999** [MetaMask/KeyringController#10]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "eth-keyring-controller" under a package
npm ERR! also called "eth-keyring-controller". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangyi/.npm/_logs/2018-03-29T09_50_04_581Z-debug.log

**Comment by danfinlay** [comment]
I haven't seen this before, and we do not include the module as a dependency of itself, so I'm not sure what could cause this. Could you provide a reproduction repo for this error?

**Comment by kumavis** [comment]
seems like they accidently tried to install the module into the cloned repo of the module
