### ISSUE TITLE
Two keyrings get created in an unintended way

### ISSUE THREAD

**Issue by JonnyBurger** [MetaMask/KeyringController#19]
This is another issue that I think does not lead to a bug in the end product, but I think is unintended and could potentially be dangerous when developing the extension further.

On line 160 and onwards:

```javascript
const keyring = new Keyring(opts)
return keyring.deserialize(opts)
.then((accounts) => {
  return this.checkForDuplicate(type, accounts)
})
```

I don't know if you realize that you create a keyring assign it to a variable and then override it immediately (assuming an HD Key).

What I fear is that by accident the wrong seed phrase can be read, like this:

```javascript
const keyring = new Keyring(opts)
// This seed will be overidden by the next line
const seed = keyring.mnemonic
return keyring.deserialize(opts)
.then((accounts) => {
  const seed2 = keyring.mnemonic
  // Not anymore the same as above
  // seed !== seed2
})
```

Why this happens is pretty obvious when reading the `eth-hd-keyring` source code.

It also does the unncecessary work of generating a seed, private key etc. twice.

**Comment by danfinlay** [comment]
Good catch, thank you, we should not call both of these in order:

```
const keyring = new Keyring(opts)
return keyring.deserialize(opts)
```
