### ISSUE TITLE
Question: how I can deal with randombytes dependency of eth-keyring-controller?

### ISSUE THREAD

**Issue by ko1ebayev** [MetaMask/KeyringController#198]
Hey! Getting this error when trying to instantiate new eth-keyring-controller class in my background script environment:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/47644077/220557098-4fe15340-eade-458e-8bca-7b0646a60763.png">

So service worker registration fails, I am using "@metamask/eth-keyring-controller": "^10.0.0"
Pls help!

**Comment by mcmire** [comment]
Hi @ko1ebayev. We see some code, but what's the error?

**Comment by ko1ebayev** [comment]
Hey! code that gives an error is just a `const keyringController = new KeyringController({})`, content on pic is a peace of code after webpack build.  
Btw, I solved this. The documentation is not complete regarding the complete lib setup. For complete setup we need a lot of polyfills. Im using Webpack 5 and typescript in my project, so the list of polyfills is:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/47644077/220555178-a556b134-f8da-4f6e-9699-6e8bf301fe5e.png">
And the second thing, I used `webpack.ProvidePlugin` to setup `global` and `process` identifiers for my build:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/47644077/220555808-6a0d4985-b9e3-4349-832f-507235f42cd8.png">

**Comment by mcmire** [comment]
Got it, thanks for posting an update and glad you figured it out @ko1ebayev. I agree about the lack of documentation around polyfills. We are revamping this library, but for the time being I've noted this in #199 so it doesn't get lost. Since I answered your question I'll close this issue now!
