### ISSUE TITLE
Returns the new address at cb of addNewAccount

### ISSUE THREAD

**Issue by watilde** [MetaMask/KeyringController#3]
I was working on this issue https://github.com/MetaMask/metamask-extension/issues/2349 and turned out it would be easier if `addNewAccount` returns the new address instead of the state Object, but I'd like to avoid breaking change with this proposal...

Is there any way to know the new address in the callback of `addNewAccount`?

**Comment by danfinlay** [comment]
That's a reasonable difference, but I agree, I want to avoid breaking changes.

You could request accounts before calling `addNewAccount` and check the difference, although that's pretty hacky. It also should be the last address in the array, but that sounds fragile.

**Comment by watilde** [comment]
Thx for the suggestions. I'd try `getAccounts` in the `metamask-controller` and returns the one unique created address to the actions!

Closing as resolved.
